### ISSUE TITLE
Pictures not showing up

### ISSUE THREAD

**Issue by jcvignoli** [wpreadme2markdown/wp2md#2]
Hi,

I reported in the php composer [version that issue](https://github.com/wpreadme2markdown/wp-readme-to-markdown/issues/27).

Since I also use the shell version, would it be possible to fix the bug in this version as well?

Thanks so much !

**Comment by sunchaserinfo** [comment]
Are you using the latest version?

```
$ php wp2md.phar --version
WP Readme to Markdown CLI 4.0.1
WP Readme to Markdown Library 4.0.1
```

**Comment by jcvignoli** [comment]
You're correct, I hadn't updated.

Now it works perfectly!

Thanks very much for your work. It's really usefull!
