### ISSUE TITLE
Fatal error:  Uncaught TypeError: trim() expects parameter 1

### ISSUE THREAD

**Issue by jcvignoli** [wpreadme2markdown/wp2md#3]
Hi,

I get a fatal error with v4.0.1 when converting my readme.

The code I use:
```
include("/working-env/vendor/autoload.php");
$readme="/README.txt";
$markdown = `\WPReadme2Markdown\Converter::convert($readme);
```

(I edited absolute paths in the example)

```
PHP Notice:  Undefined offset: 1 in vendor/wpreadme2markdown/wpreadme2markdown/src/Converter.php on line 107
PHP Fatal error:  Uncaught TypeError: trim() expects parameter 1 to be string, null given in vendor/wpreadme2markdown/wpreadme2markdown/src/Converter.php:107
Stack trace:
#0 vendor/wpreadme2markdown/wpreadme2markdown/src/Converter.php(107): trim()
#1 vendor/wpreadme2markdown/wpreadme2markdown/src/Converter.php(112): WPReadme2Markdown\Converter::getPluginSlug()
#2 vendor/wpreadme2markdown/wpreadme2markdown/src/Converter.php(33): WPReadme2Markdown\Converter::convertScreenshots()
#3 tmp/convert_readme.php(4): WPReadme2Markdown\Converter::convert()
#4 {main}
  thrown in vendor/wpreadme2markdown/wpreadme2markdown/src/Converter.php on line 107
```
What am I doing wrong?

**Comment by sunchaserinfo** [comment]
It needs a better error message, yes, but it meants that your readme is missing the top header

If that's really the code you're using, you should read the contents of the file \
`$readme=file_get_contents("/README.txt");`

**Comment by jcvignoli** [comment]
Ok, now I get it, could you update the readme accordingly?

One more question: where is saved the readme.md? I can't find it in the location where the readme.txt is, where I ran the php script, or even where the wpreadme2markdown library is.

Thanks!

**Comment by sunchaserinfo** [comment]
It's just stored in the variable. The library itself does not deal with files, only with strings, you need to read and write files yourself

```php
<?php

require '..../autoload.php';

$wp = file_get_contents('./readme.txt');
$md = \WPReadme2Markdown\Converter::convert($wp);
file_put_contents('./readme.md', $md);
```

you can find the example in the cli code: https://github.com/wpreadme2markdown/wp2md/blob/master/src/Convert.php#L33

**Comment by jcvignoli** [comment]
Cristal clear. Thanks so much for the explaination.
