### ISSUE TITLE
Screenshots are not retrieved

### ISSUE THREAD

**Issue by jcvignoli** [wpreadme2markdown/wp2md#5]
Hi there,

I'm using `WP Readme to Markdown CLI 4.1.1` and `WP Readme to Markdown Library 4.1.0`. Screenshots from WP readme are not correctly updated, and an "[Missing image]" is added instead the correct image link and text.

It is not related to the latest wp2md version, I used to have this issue a while ago.

This bug happens with the following readme:
https://github.com/jcvignoli/lumiere-movies/blob/master/src/README.txt

Thanks for your work

**Comment by sunchaserinfo** [comment]
It is connected, broken by library 4.1.0, only png screenshots were detected

**Comment by sunchaserinfo** [comment]
Fixed in lib 4.1.1 / cli 4.1.2

**Comment by sunchaserinfo** [comment]
In your specific case also the slug may be detected incorrectly and you need to add `--slug=lumiere-movies` cli param

**Comment by jcvignoli** [comment]
Thanks, I confirm it works!
